In [36]:
import pandas as pd

In [37]:
df = pd.read_csv(r"C:\Users\hp\Downloads\Expresso_churn_dataset (1).csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

In [38]:
df.head()

,user_id,REGION,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,MRG,REGULARITY,TOP_PACK,FREQ_TOP_PACK,CHURN
0,00000bfd7d50f01092811bc0c8d7b0d6fe7c3596,FATICK,K > 24 month,4250.0,15.0,4251.0,1417.0,17.0,4.0,388.0,46.0,1.0,1.0,2.0,NO,54,On net 200F=Unlimited _call24H,8.0,0
37,000134b94b87f70dc30597aa19598fbeaa70dc7f,DAKAR,K > 24 month,10400.0,24.0,10900.0,3633.0,26.0,11815.0,12.0,59.0,3.0,0.0,1.0,NO,54,"Data:490F=1GB,7d",8.0,0
170,0004f3a6671684d984c83c2cfa30647665dd430b,DAKAR,K > 24 month,3000.0,6.0,2999.0,1000.0,7.0,515.0,15.0,0.0,0.0,0.0,0.0,NO,58,"Data:490F=1GB,7d",5.0,0
561,001191f7d3aec518be9fcd550015fb45826c3ed2,THIES,K > 24 month,2750.0,6.0,2748.0,916.0,6.0,0.0,33.0,1.0,22.0,0.0,8.0,NO,39,Mixt 250F=Unlimited_call24H,1.0,0
635,0013b5ca16d87ad1d286fe66d46754b80b9e22fc,DAKAR,K > 24 month,11700.0,21.0,12698.0,4233.0,33.0,2.0,170.0,249.0,15.0,6.0,3.0,NO,62,All-net 500F=2000F;5d,17.0,0

In [39]:
df['REGION'].unique()

array(['FATICK', 'DAKAR', 'THIES', 'KAOLACK', 'TAMBACOUNDA', 'ZIGUINCHOR',
       'SAINT-LOUIS', 'DIOURBEL', 'MATAM', 'KAFFRINE', 'LOUGA', 'KOLDA',
       'SEDHIOU', 'KEDOUGOU'], dtype=object)

In [40]:
df.columns

Index(['user_id', 'REGION', 'TENURE', 'MONTANT', 'FREQUENCE_RECH', 'REVENUE',
       'ARPU_SEGMENT', 'FREQUENCE', 'DATA_VOLUME', 'ON_NET', 'ORANGE', 'TIGO',
       'ZONE1', 'ZONE2', 'MRG', 'REGULARITY', 'TOP_PACK', 'FREQ_TOP_PACK',
       'CHURN'],
      dtype='object')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10839 entries, 0 to 2153831
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   user_id         10839 non-null  object
 1   REGION          10839 non-null  object
 2   TENURE          10839 non-null  object
 3   MONTANT         10839 non-null  float64
 4   FREQUENCE_RECH  10839 non-null  float64
 5   REVENUE         10839 non-null  float64
 6   ARPU_SEGMENT    10839 non-null  float64
 7   FREQUENCE       10839 non-null  float64
 8   DATA_VOLUME     10839 non-null  float64
 9   ON_NET          10839 non-null  float64
 10  ORANGE          10839 non-null  float64
 11  TIGO            10839 non-null  float64
 12  ZONE1           10839 non-null  float64
 13  ZONE2           10839 non-null  float64
 14  MRG             10839 non-null  object
 15  REGULARITY      10839 non-null  int64
 16  TOP_PACK        10839 non-null  object
 17  FREQ_TOP_PACK   10839 non-null  float64
 18  CHURN           10839 non-null  int64
dtypes: float64(12), int64(2), object(5)
memory usage: 1.7+ MB

In [42]:
df.isnull().sum()

user_id           0
REGION            0
TENURE            0
MONTANT           0
FREQUENCE_RECH    0
REVENUE           0
ARPU_SEGMENT      0
FREQUENCE         0
DATA_VOLUME       0
ON_NET            0
ORANGE            0
TIGO              0
ZONE1             0
ZONE2             0
MRG               0
REGULARITY        0
TOP_PACK          0
FREQ_TOP_PACK     0
CHURN             0
dtype: int64

In [43]:
#df['REGION']= df['REGION'].fillna(df['REGION'].mode()[0])
#df['TOP_PACK']= df['TOP_PACK'].fillna(df['TOP_PACK'].mode()[0])
#float_columns = df.select_dtypes(include='Float64').columns
#df[float_columns] = df[float_columns].fillna(df[float_columns].median())

In [44]:
df.dropna(inplace=True)

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.shape

(10839, 19)

In [47]:
import numpy as np

In [48]:
from scipy.stats import zscore

In [49]:
numeric_df = df.select_dtypes(include='number')

In [50]:
numeric_df = numeric_df[(np.abs(zscore(numeric_df))< 3).all(axis = 1)]

In [51]:
numeric_df.shape

(9498, 14)

In [52]:
categorical_df = df.select_dtypes(include = 'object')

In [53]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [54]:
le = LabelEncoder()
categorical_columns = ['REGION','TENURE', 'MRG','TOP_PACK' ]
categorical_df[categorical_columns] = categorical_df[categorical_columns].apply(lambda col: le.fit_transform(col))

In [55]:
joined_df = categorical_df.join(numeric_df, how = 'inner')

In [56]:
joined_df

,user_id,REGION,TENURE,MRG,TOP_PACK,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,REGULARITY,FREQ_TOP_PACK,CHURN
0,00000bfd7d50f01092811bc0c8d7b0d6fe7c3596,2,7,0,51,4250.0,15.0,4251.0,1417.0,17.0,4.0,388.0,46.0,1.0,1.0,2.0,54,8.0,0
37,000134b94b87f70dc30597aa19598fbeaa70dc7f,0,7,0,21,10400.0,24.0,10900.0,3633.0,26.0,11815.0,12.0,59.0,3.0,0.0,1.0,54,8.0,0
170,0004f3a6671684d984c83c2cfa30647665dd430b,0,7,0,21,3000.0,6.0,2999.0,1000.0,7.0,515.0,15.0,0.0,0.0,0.0,0.0,58,5.0,0
561,001191f7d3aec518be9fcd550015fb45826c3ed2,12,7,0,47,2750.0,6.0,2748.0,916.0,6.0,0.0,33.0,1.0,22.0,0.0,8.0,39,1.0,0
635,0013b5ca16d87ad1d286fe66d46754b80b9e22fc,0,7,0,7,11700.0,21.0,12698.0,4233.0,33.0,2.0,170.0,249.0,15.0,6.0,3.0,62,17.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152712,ffd68ad289fd2d46347b7b48619671d532da12fa,0,7,0,33,12100.0,28.0,11661.0,3887.0,25.0,0.0,204.0,218.0,36.0,0.0,1.0,57,8.0,0
2153142,ffe457524394dca68e4d8ce1b2a096682d1ae879,8,5,0,17,3000.0,12.0,2989.0,996.0,18.0,4590.0,3.0,48.0,6.0,0.0,0.0,40,6.0,0
2153483,ffee32230918433bcbac7cd6d9004fe79ef95053,0,7,0,37,12000.0,8.0,11539.0,3846.0,9.0,9179.0,1405.0,384.0,42.0,0.0,2.0,61,3.0,0
2153547,fff01392a3349a53a2936bf35ed25db7f11db14e,0,7,0,7,14600.0,27.0,15599.0,5200.0,29.0,0.0,32.0,304.0,13.0,2.0,2.0,52,28.0,0
2153831,fff8b64302bda7f59ff196af759e1de7c4215f6d,0,7,0,34,40000.0,5.0,23197.0,7732.0,18.0,662.0,1143.0,568.0,75.0,47.0,12.0,61,1.0,0

In [57]:
X = joined_df.drop(columns = ['CHURN','user_id'])
Y = joined_df['CHURN']

In [58]:
X_train, X_test, Y_train, Y_test = train_test_split ( X, Y, test_size=0.2, random_state= 70)

In [59]:
model = RandomForestClassifier(n_estimators= 5, max_depth=5)

In [60]:
model.fit(X_train, Y_train)

RandomForestClassifier(max_depth=5, n_estimators=5)

In [61]:
prediction = model.predict(X_test)

In [62]:
accuracy_score(Y_test, prediction)

1.0

In [63]:
import joblib
joblib.dump(model,r'C:\Users\hp\Downloads\Expresso_churn_dataset (1).csv' )

['C:\\Users\\hp\\Downloads\\Expresso_churn_dataset (1).csv']